DELETE FROM  T_NPRP_BFD_CONF_SCARICHI WHERE ID_FLUSSO = '75GGEN85';

DELETE FROM  T_NPRP_BFD_CONF_SCARICHI WHERE ID_FLUSSO = '75GGEN86';

DELETE FROM  T_NPRP_BFD_CONF_SCARICHI WHERE ID_FLUSSO = '75GGEN87';

DELETE FROM T_PPID_BFD_CONF_SCARICHI WHERE ID_FLUSSO = '75GGEN88';

DELETE FROM T_PPID_BFD_CONF_SCARICHI WHERE ID_FLUSSO = '75GGEN89';

DELETE FROM T_PPID_BFD_CONF_SCARICHI WHERE ID_FLUSSO = '75GGEN90';

-- 75GGEN85 -  T_NPRP_SEZIONE
INSERT INTO T_NPRP_BFD_CONF_SCARICHI
(
	ID_FLUSSO,
	TIPO_REC_DETTAGLIO,
	TIPO_REC_TESTA,
	TIPO_REC_CODA,
	SQL_DETTAGLIO,
	NOME_FLUSSO_OUT,
	LST_NOMI_CAMPI,
	LST_FORMAT_CAMPI,
	LST_TYPE_CAMPI,
	PERIODICITA,
	TIPO_SCARICO,
	COD_ABI,
	LENGTH_TESTA,
	LENGTH_CODA,
	ORA_SCHED_TWS 
)VALUES('75GGEN85',
	'01',
	'00',
	'99',
	'SELECT ''01'' AS TIPO_RECORD, ''0'' AS FLG_DELETE, NULL AS TMS_DELETE, ED.* , O.ABI as COD_ABI, (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) as TMS_INS_UPD_BFD  FROM T_NPRP_SEZIONE ED left join T_NPRP_ABC O on O.ID_OFFERTA = ED.ID_OFFERTA WHERE (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) >= TO_TIMESTAMP(''%1$s'', ''YYYYMMDDHH24MISSFF'') AND (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) <= TO_TIMESTAMP(''%2$s'', ''YYYYMMDDHH24MISSFF'')',
	'75GGEN85.MULTI',
	'TIPO_RECORD,FLG_DELETE,TMS_DELETE,ID_SEZIONE,ID_OFFERTA,CODICE,DESCRIZIONE,FILIALE,CATEGORIA,NUM_CC,NUM_DEP,COD_CONTO,DES_CONTO,CC_EROGAZIONE,TIMESTAMP_INSERIMENTO,TIMESTAMP_MODIFICA,COD_ABI,TMS_INS_UPD_BFD',
	'%1$2.2s%2$1.1s%3$26.26s%4$+012.0f%5$+012.0f%6$25.25s%7$75.75s%8$5.5s%9$4.4s%10$10.10s%11$11.11s%12$30.30s%13$75.75s%14$15.15s%15$26.26s%16$26.26s%17$5.5s%18$26.26s',
	'String,String,Timestamp,BigDecimal,BigDecimal,String,String,String,String,String,String,String,String,String,Timestamp,Timestamp,String,Timestamp', 
	'G',
	'D',
	'MULTI',
	'386','386','21:20:00');

-- 75GGEN86 -  T_NPRP_RIGA
INSERT INTO T_NPRP_BFD_CONF_SCARICHI
(
	ID_FLUSSO,
	TIPO_REC_DETTAGLIO,
	TIPO_REC_TESTA,
	TIPO_REC_CODA,
	SQL_DETTAGLIO,
	NOME_FLUSSO_OUT,
	LST_NOMI_CAMPI,
	LST_FORMAT_CAMPI,
	LST_TYPE_CAMPI,
	PERIODICITA,
	TIPO_SCARICO,
	COD_ABI,
	LENGTH_TESTA,
	LENGTH_CODA,
	ORA_SCHED_TWS
)VALUES('75GGEN86',
	'01',
	'00',
	'99',
	'SELECT ''01'' AS TIPO_RECORD, ''0'' AS FLG_DELETE, NULL AS TMS_DELETE, ED.* , O.ABI as COD_ABI, (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) as TMS_INS_UPD_BFD  FROM T_NPRP_RIGA ED left join t_nprp_sezione s on s.id_sezione = ed.id_sezione
left join T_NPRP_ABC O on O.ID_OFFERTA = S.ID_OFFERTA WHERE (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) >= TO_TIMESTAMP(''%1$s'', ''YYYYMMDDHH24MISSFF'') AND (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) <= TO_TIMESTAMP(''%2$s'', ''YYYYMMDDHH24MISSFF'')',
	'75GGEN86.MULTI',
	'TIPO_RECORD,FLG_DELETE,TMS_DELETE,ID_RIGA,ID_SEZIONE,FLAG_30_GG,CONTROVALORE,TIPO_RIGA,DES_TIPO_RIGA,TIMESTAMP_INSERIMENTO,TIMESTAMP_MODIFICA,COD_ABI,TMS_INS_UPD_BFD',
	'%1$2.2s%2$1.1s%3$26.26s%4$+012.0f%5$+012.0f%6$3.3s%7$+017.2f%8$10.10s%9$75.75s%10$26.26s%11$26.26s%12$5.5s%13$26.26s',
	'String,String,Timestamp,BigDecimal,BigDecimal,String,BigDecimal,String,String,Timestamp,Timestamp,String,Timestamp', 
	'G',
	'D',
	'MULTI',
	'241','241','21:20:00');

-- 75GGEN87 -  T_NPRP_SPESA
INSERT INTO T_NPRP_BFD_CONF_SCARICHI
(
	ID_FLUSSO,
	TIPO_REC_DETTAGLIO,
	TIPO_REC_TESTA,
	TIPO_REC_CODA,
	SQL_DETTAGLIO,
	NOME_FLUSSO_OUT,
	LST_NOMI_CAMPI,
	LST_FORMAT_CAMPI,
	LST_TYPE_CAMPI,
	PERIODICITA,
	TIPO_SCARICO,
	COD_ABI,
	LENGTH_TESTA,
	LENGTH_CODA,
	ORA_SCHED_TWS
)VALUES('75GGEN87',
	'01',
	'00',
	'99',
	'SELECT ''01'' AS TIPO_RECORD, ''0'' AS FLG_DELETE, NULL AS TMS_DELETE, ED.* , O.ABI as COD_ABI, (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) as TMS_INS_UPD_BFD  FROM T_NPRP_SPESA ED left join t_nprp_riga r on r.id_riga = ed.id_riga
left join t_nprp_sezione s on s.id_sezione = r.id_sezione
left join T_NPRP_ABC O on O.ID_OFFERTA = S.ID_OFFERTA WHERE (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) >= TO_TIMESTAMP(''%1$s'', ''YYYYMMDDHH24MISSFF'') AND (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) <= TO_TIMESTAMP(''%2$s'', ''YYYYMMDDHH24MISSFF'')',
	'75GGEN87.MULTI',
	'TIPO_RECORD,FLG_DELETE,TMS_DELETE,ID_SPESA,ID_RIGA,COD_SPESA,DES_SPESA,TRATTAMENTO,RISOLUZIONE,PERCENTUALE,IMPORTO_STANDARD,IMPORTO_CLIENTE,TIMESTAMP_INSERIMENTO,TIMESTAMP_MODIFICA,COD_ABI,TMS_INS_UPD_BFD',
	'%1$2.2s%2$1.1s%3$26.26s%4$+012.0f%5$+012.0f%6$15.15s%7$75.75s%8$3.3s%9$3.3s%10$+09.4f%11$+017.2f%12$+017.2f%13$26.26s%14$26.26s%15$5.5s%16$26.26s',
	'String,String,Timestamp,BigDecimal,BigDecimal,String,String,String,String,BigDecimal,BigDecimal,BigDecimal,Timestamp,Timestamp,String,Timestamp', 
	'G',
	'D',
	'MULTI',
	'275','275','21:20:00');

-- 75GGEN88 -  T_PPID_SEZIONE
INSERT INTO T_PPID_BFD_CONF_SCARICHI
(
	ID_FLUSSO,
	TIPO_REC_DETTAGLIO,
	TIPO_REC_TESTA,
	TIPO_REC_CODA,
	SQL_DETTAGLIO,
	NOME_FLUSSO_OUT,
	LST_NOMI_CAMPI,
	LST_FORMAT_CAMPI,
	LST_TYPE_CAMPI,
	PERIODICITA,
	TIPO_SCARICO,
	COD_ABI,
	LENGTH_TESTA,
	LENGTH_CODA,
	ORA_SCHED_TWS
)VALUES('75GGEN88',
	'01',
	'00',
	'99',
	'SELECT ''01'' AS TIPO_RECORD, ''0'' AS FLG_DELETE, NULL AS TMS_DELETE, ED.* , O.ABI as COD_ABI, (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) as TMS_INS_UPD_BFD  FROM T_PPID_SEZIONE ED left join T_PPID_ABC O on O.ID_OFFERTA = ED.ID_OFFERTA WHERE (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) >= TO_TIMESTAMP(''%1$s'', ''YYYYMMDDHH24MISSFF'') AND (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) <= TO_TIMESTAMP(''%2$s'', ''YYYYMMDDHH24MISSFF'')',
	'75GGEN88.MULTI',
	'TIPO_RECORD,FLG_DELETE,TMS_DELETE,ID_SEZIONE,ID_OFFERTA,CODICE,DESCRIZIONE,FILIALE,CATEGORIA,NUM_CC,NUM_DEP,COD_CONTO,DES_CONTO,CC_EROGAZIONE,TIMESTAMP_INSERIMENTO,TIMESTAMP_MODIFICA,COD_ABI,TMS_INS_UPD_BFD',
	'%1$2.2s%2$1.1s%3$26.26s%4$+012.0f%5$+012.0f%6$25.25s%7$75.75s%8$5.5s%9$4.4s%10$10.10s%11$11.11s%12$30.30s%13$75.75s%14$15.15s%15$26.26s%16$26.26s%17$5.5s%18$26.26s',
	'String,String,Timestamp,BigDecimal,BigDecimal,String,String,String,String,String,String,String,String,String,Timestamp,Timestamp,String,Timestamp', 
	'G',
	'D',
	'MULTI',
	'386','386','21:00:00');

-- 75GGEN89 -  T_PPID_RIGA
INSERT INTO T_PPID_BFD_CONF_SCARICHI
(
	ID_FLUSSO,
	TIPO_REC_DETTAGLIO,
	TIPO_REC_TESTA,
	TIPO_REC_CODA,
	SQL_DETTAGLIO,
	NOME_FLUSSO_OUT,
	LST_NOMI_CAMPI,
	LST_FORMAT_CAMPI,
	LST_TYPE_CAMPI,
	PERIODICITA,
	TIPO_SCARICO,
	COD_ABI,
	LENGTH_TESTA,
	LENGTH_CODA,
	ORA_SCHED_TWS
)VALUES('75GGEN89',
	'01',
	'00',
	'99',
	'SELECT ''01'' AS TIPO_RECORD, ''0'' AS FLG_DELETE, NULL AS TMS_DELETE, ED.* , O.ABI as COD_ABI, (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) as TMS_INS_UPD_BFD  FROM T_PPID_RIGA ED left join t_ppid_sezione s on s.id_sezione = ed.id_sezione
left join T_ppid_ABC O on O.ID_OFFERTA = S.ID_OFFERTA WHERE (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) >= TO_TIMESTAMP(''%1$s'', ''YYYYMMDDHH24MISSFF'') AND (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) <= TO_TIMESTAMP(''%2$s'', ''YYYYMMDDHH24MISSFF'')',
	'75GGEN89.MULTI',
	'TIPO_RECORD,FLG_DELETE,TMS_DELETE,ID_RIGA,ID_SEZIONE,FLAG_30_GG,CONTROVALORE,TIPO_RIGA,DES_TIPO_RIGA,TIMESTAMP_INSERIMENTO,TIMESTAMP_MODIFICA,COD_ABI,TMS_INS_UPD_BFD',
	'%1$2.2s%2$1.1s%3$26.26s%4$+012.0f%5$+012.0f%6$3.3s%7$+017.2f%8$10.10s%9$75.75s%10$26.26s%11$26.26s%12$5.5s%13$26.26s',
	'String,String,Timestamp,BigDecimal,BigDecimal,String,BigDecimal,String,String,Timestamp,Timestamp,String,Timestamp', 
	'G',
	'D',
	'MULTI',
	'241','241','21:00:00');

-- 75GGEN90 -  T_PPID_SPESA
INSERT INTO T_PPID_BFD_CONF_SCARICHI
(
	ID_FLUSSO,
	TIPO_REC_DETTAGLIO,
	TIPO_REC_TESTA,
	TIPO_REC_CODA,
	SQL_DETTAGLIO,
	NOME_FLUSSO_OUT,
	LST_NOMI_CAMPI,
	LST_FORMAT_CAMPI,
	LST_TYPE_CAMPI,
	PERIODICITA,
	TIPO_SCARICO,
	COD_ABI,
	LENGTH_TESTA,
	LENGTH_CODA,
	ORA_SCHED_TWS
)VALUES('75GGEN90',
	'01',
	'00',
	'99',
	'SELECT ''01'' AS TIPO_RECORD, ''0'' AS FLG_DELETE, NULL AS TMS_DELETE, ED.* , O.ABI as COD_ABI, (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) as TMS_INS_UPD_BFD  FROM T_PPID_SPESA ED left join t_ppid_riga r on r.id_riga = ed.id_riga
left join t_ppid_sezione s on s.id_sezione = r.id_sezione
left join T_ppid_ABC O on O.ID_OFFERTA = S.ID_OFFERTA WHERE (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) >= TO_TIMESTAMP(''%1$s'', ''YYYYMMDDHH24MISSFF'') AND (CASE WHEN ED.TIMESTAMP_MODIFICA IS NOT NULL AND ED.TIMESTAMP_MODIFICA >ED.TIMESTAMP_INSERIMENTO THEN ED.TIMESTAMP_MODIFICA ELSE ED.TIMESTAMP_INSERIMENTO END ) <= TO_TIMESTAMP(''%2$s'', ''YYYYMMDDHH24MISSFF'')',
	'75GGEN90.MULTI',
	'TIPO_RECORD,FLG_DELETE,TMS_DELETE,ID_SPESA,ID_RIGA,COD_SPESA,DES_SPESA,TRATTAMENTO,RISOLUZIONE,PERCENTUALE,IMPORTO_STANDARD,IMPORTO_CLIENTE,TIMESTAMP_INSERIMENTO,TIMESTAMP_MODIFICA,COD_ABI,TMS_INS_UPD_BFD',
	'%1$2.2s%2$1.1s%3$26.26s%4$+012.0f%5$+012.0f%6$15.15s%7$75.75s%8$3.3s%9$3.3s%10$+09.4f%11$+017.2f%12$+017.2f%13$26.26s%14$26.26s%15$5.5s%16$26.26s',
	'String,String,Timestamp,BigDecimal,BigDecimal,String,String,String,String,BigDecimal,BigDecimal,BigDecimal,Timestamp,Timestamp,String,Timestamp', 
	'G',
	'D',
	'MULTI',
	'275','275','21:00:00');


